### PR TITLE
Fix extract function code action being triggered too early

### LINKED ISSUE #208: "extract function" is triggered unexpectedly on versions from 2.0.0 to 2.2.1 when using with VSCode Live Share
## Expected Behavior

When using `ms-vsliveshare.vsliveshare`, and `elmtooling.elm-ls-vscode` version 2.0.0 or higher, both participants should be able to use language server features like type hints or autocomplete without uncontrolled creation of code blocks.

## Current Behavior

When using `ms-vsliveshare.vsliveshare` and `elmtooling.elm-ls-vscode` versions from 2.0.0 to 2.2.1 when guest participant writes some code that leads to autocomplete, instead a `newFunction` definition is created and some code is extracted to it. It repeats approximately every second.

**On `elmtooling.elm-ls-vscode` version 1.5.3 the bug is not reproduced, everything seems to be fine.**

## Possible Solution

Check why the `extract function` feature is triggered. 

I believe that it's not LiveShare's fault, because other language servers (TypeScript, F#, Haskell) work fine with Live Share and our configurations.

## Steps to Reproduce

1. Start a live share session and create a new elm module like this:
```elm
module Test exposing (..)
x =
    List.map
```
2. Allow a guest participant to connect

3. Guest participants types in an open parenthesis like this:
```elm
module Test exposing (..)
x =
    List.map (
```
4. The extension performs an "extract function" action (added in 2.0.0), which repeatedly adds the following definition with a short time interval (let's say every 1 second) until both participants move their text cursor away from this place.
```elm
module Test exposing (..)
x =
    List.map newFunction
newFunction : ()
newFunction =
    ()
```

## Context

I use VSCode with Live Share to collaborate on an Elm codebase.

### Configuration A (as a live share host)

* `elmtooling.elm-ls-vscode` version: from 2.0.0 to 2.2.1
* `ms-vsliveshare.vsliveshare` version: v1.0.4673
* Editor name and version: VSCode 1.59.0 arm64
* Environment name and version: Node.js 15.6.2
* Operating System and version: macOS Big Sur 11.5.2, Apple M1

### Configuration B (also as a live share host)

* `elmtooling.elm-ls-vscode` version: from 2.0.0 to 2.2.1
* `ms-vsliveshare.vsliveshare` version: v1.0.4673
* Editor name and version: VSCode 1.59.1 x64
* Environment name and version: Node.js 16.5.0
* Operating System and version: macOS High Sierra 10.13.6, Intel Core i7

### PR DESCRIPTION
**Pull request by jmbockhorst**
We were incorrectly running the extract method code action on the resolve request. The resolve request is just to fill in the edits, not to run the request. Instead we need to pass a command that will triggered after the code action is triggered. Most of the time, the code action was resolved when the code action was triggered, so it didn't cause any issues. But recently the Live Share extension changed it to eagerly resolve all code action when they are requested. This caused us to manually trigger the extract function every time a code action was requested, but not triggered.

Fixes #208.

### CODE REVIEW

File: client/src/extension.ts [hunk 1]
```diff
@@ -188,6 +190,27 @@ export function deactivate(): Thenable<void> | undefined {
   }
   return Promise.all(promises).then(() => undefined);
 }
+
+const didApplyRefactoringCommandId = "elm.didApplyRefactoring";
```
Comment (jmbockhorst) [inline client/src/extension.ts:194]: I know in other places you had to add an `extensionId` postfix. Is this necessary here? I don't feel like it should be and I'm not sure how to do it either.

Comment (razzeee) [reply client/src/extension.ts:194]: You need to pass the `workspaceId` to the function registering. I'll have a look at the branch.

Comment (razzeee) [reply client/src/extension.ts:194]: Ah, right, the other reference is the problem.

Comment (jmbockhorst) [reply client/src/extension.ts:194]: Maybe we just need to add a check to make sure this command only gets registered once?

Comment (razzeee) [reply client/src/extension.ts:194]: We can try, but I don't think that's enough

Comment (jmbockhorst) [reply client/src/extension.ts:194]: Can you explain why?

Comment (razzeee) [reply client/src/extension.ts:194]: I think I'm wrong, from testing, doing 

```
if (!isRegistered) {
          registerDidApplyRefactoringCommand(context);
          isRegistered = true;
        }
```

seems to work fine. The code before also seemed to work fine, but had an error in the debug console.

Comment (jmbockhorst) [reply client/src/extension.ts:198]: Or instead can we just pull it outside of the forEach loop?

Comment (razzeee) [reply client/src/extension.ts:198]: Makes way more sense :)
